# frozen_string_literal: true

class AddAutoGeneratedToZonePairVehiclePricings < ActiveRecord::Migration[8.0]
  def change
    add_column :zone_pair_vehicle_pricings, :auto_generated, :boolean, default: false
  end
end
